module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'subject-case': [0],
    'header-max-length': [2, 'always', 100],
    // Custom rule: block AI attribution in commits
    'no-claude-attribution': [2, 'always']
  },
  plugins: [{
    rules: {
      'no-claude-attribution': ({ raw }) => {
        const banned = [
          'co-authored-by: claude',
          'generated by claude',
          'generated by claude code',
          'ai-assisted',
          'claude code',
          '🤖'
        ]
        const lower = raw.toLowerCase()
        const match = banned.find(b => lower.includes(b))
        return [
          !match,
          match ? `AI attribution banned in commits: "${match}" found. Remove it.` : ''
        ]
      }
    }
  }]
}
